/** EN ESTE ARCHIVO ESTARAN TODAS LAS FUNCIONES DE JAVA SCRIPT NECESARIAS PARA LA DINAMICA DE LA APOLICACION. */

/** POR DEFECTO YA CONTIENE EL DOMContentLoades Y EN ESTE ES DONDE HAREMOS LLAMAR LAS FUNCIONES POR SI SOLAS CUANDO YA SE HA  CARGADO TODA LA APLICACION EN EL NA VEGADOR COMO DARK MODE, EVENTOS DE CLICK, SCROLL, ENTRE OTROS */

/** RECORDEMOS QUE EN LA FUNCUON DE EVENTLISTENERS() ES DONDE SE AGREGARAN LOS EVENTOS POR CLICK */
// ES6 Modules or TypeScript
import ApexCharts from './apexcharts.esm.js';
import Cropper from './cropper.esm.js';






  